- src/sklearn_evaluation/compute.py
- src/sklearn_evaluation/evaluator.py
- src/sklearn_evaluation/exceptions.py
- src/sklearn_evaluation/metrics.py
- src/sklearn_evaluation/plot/classification.py
- src/sklearn_evaluation/plot/grid_search.py
- src/sklearn_evaluation/plot/precision_recall.py
- src/sklearn_evaluation/plot/roc.py
- src/sklearn_evaluation/plot/validation_curve.py
- src/sklearn_evaluation/validate.py
Hey!
I just fixed some typos in the plot module. Most of them also appear on the docs, so i thought it would be nice to have them fixed.  
Thanks for the neat package :)
> Fix typos in sklearn_evaluation.plot module

- src/sklearn_evaluation/SQLiteTracker.py
- src/sklearn_evaluation/evaluator.py
- src/sklearn_evaluation/nb/NotebookCollection.py
- src/sklearn_evaluation/plot/classification.py
- src/sklearn_evaluation/plot/grid_search.py
- src/sklearn_evaluation/plot/learning_curve.py
- src/sklearn_evaluation/plot/metrics.py
- src/sklearn_evaluation/plot/precision_recall.py
- src/sklearn_evaluation/plot/roc.py
- src/sklearn_evaluation/plot/validation_curve.py
- src/sklearn_evaluation/report/report.py
- src/sklearn_evaluation/telemetry.py
- tests/test_SQLiteTracker.py
- tests/test_skeval_telemetry.py
SKLearnEvaluationLogger decorator wraps telemetry log_api functionality and allows to generate logs for sklearn-evaluation as follows:
```
@SKLearnEvaluationLogger.log(feature='plot')
def confusion_matrix(
y_true,
y_pred,
target_names=None,
normalize=False,
cmap=None,
ax=None,
**kwargs):
pass
```
this will generate the following log:
```
{
"metadata": {
"action": "confusion_matrix"
"feature": "plot",
"args": {
"target_names": "None",
"normalize": "False",
"cmap": "None",
"ax": "None"
}
}
}
```
** since `y_true` and `y_pred` are positional arguments without default values it won't log them
we can also use pre-defined flags when calling a function
```
return plot.confusion_matrix(self.y_true, self.y_pred, self.target_names, ax=_gen_ax())
```
which will generate the following log:
``` …
```
> SKLearnEvaluationLogger added

- docs/README.md
> Update README.md in docs

- CONTRIBUTING.md
Renamed `plot_something` to `some_algorithm`
> renamed plot_something

- CONTRIBUTING.md
> figure guideline

- .github/workflows/ci.yml
- docs/_toc.yml
- docs/quickstart/classification.md
Partial solution to the quick start guides, focusing on classification.
> Added classification quickstart

- src/sklearn_evaluation/compute.py
- tests/test_table.py
> Array type feature names

- docs/_config.yml
> change copyright to 2023

- CHANGELOG.rst
- docs/clustering/clustering_evaluation.md
- docs/quickstart/clustering.md
- examples/elbow_curve.py
- src/sklearn_evaluation/plot/clustering.py
- tests/test_clustering.py
1. `range_n_clusters` added to elbow_curve signature
2. elbow_curve still supports `n_clusters`
3. Deprecation warning added
4. AttributeError added when using `range_n_clusters` and `n_clusters` at the same time
5. Examples updated
Closes #148
> range_n_clusters added to elbow_curve signature

- .github/workflows/ci.yml
- setup.py
- src/sklearn_evaluation/plot/clustering.py
- src/sklearn_evaluation/plot/plot.py
- src/sklearn_evaluation/plot/regression.py
- src/sklearn_evaluation/plot/roc.py
- tasks.py
- tests/test_clustering.py
- tests/test_plot.py
- tests/test_regression.py
- renaming labels -> label in ROC
- fixes deprecation
- applies pending deprecation
Closes #x 
----
:books: Documentation preview :books:: https://sklearn-evaluation--205.org.readthedocs.build/en/205/
> PR for 0.9

- src/sklearn_evaluation/__init__.py
- src/sklearn_evaluation/evaluator.py
- src/sklearn_evaluation/nb/NotebookCollection.py
- src/sklearn_evaluation/nb/NotebookDatabase.py
- src/sklearn_evaluation/plot/__init__.py
- src/sklearn_evaluation/plot/classification.py
- src/sklearn_evaluation/plot/classification_report.py
- src/sklearn_evaluation/plot/grid_search.py
- src/sklearn_evaluation/plot/learning_curve.py
- src/sklearn_evaluation/plot/metrics.py
- src/sklearn_evaluation/plot/plot.py
- src/sklearn_evaluation/plot/precision_recall.py
- src/sklearn_evaluation/plot/roc.py
- src/sklearn_evaluation/plot/target_analysis.py
- src/sklearn_evaluation/plot/validation_curve.py
- src/sklearn_evaluation/table.py
Update the relative imports in sklearn-evaluation repo to absolute imports.
Closes #187 
----
:books: Documentation preview :books:: https://sklearn-evaluation--228.org.readthedocs.build/en/228/
> fix relative imports

- docs/classification/compare.md
added roc1 + roc2 for compare.md
Closes #227 
----
:books: Documentation preview :books:: https://sklearn-evaluation--234.org.readthedocs.build/en/234/
> added roc1 + roc2 for compare.md

- examples/precision_recall_multiclass.py
- src/sklearn_evaluation/plot/precision_recall.py
This change resolves #238 by adding a precision-recall multiclass example
Closes #238  
----
:books: Documentation preview :books:: https://sklearn-evaluation--241.org.readthedocs.build/en/241/
> adds precision-recall multiclass example

- docs/comparison/NotebookCollection.md
- docs/requirements.txt
Closes #x 
----
:books: Documentation preview :books:: https://sklearn-evaluation--252.org.readthedocs.build/en/252/
> testing to see if docs fail

- src/sklearn_evaluation/nb/NotebookCollection.py
- src/sklearn_evaluation/util.py
Fix Noqa coming up on docs issue
Follow the pattern in https://github.com/pycqa/flake8/issues/621
Closes https://github.com/ploomber/sklearn-evaluation/issues/246
> Fix: Noqa coming up on docs

- CHANGELOG.md
- src/sklearn_evaluation/__init__.py
- src/sklearn_evaluation/plot/classification_report.py
- src/sklearn_evaluation/plot/plot.py
- src/sklearn_evaluation/plot/util.py
- src/sklearn_evaluation/tracker.py
- tests/test_classification_report.py
- I noticed the [tracker tutorial](https://sklearn-evaluation.ploomber.io/en/latest/comparison/SQLiteTracker.html#rendering-plots-in-table-view) had a lot of duplicated plots (see the link), this fixes it
- this also applies a pending deprecation on ClassificationReport
Closes #x
> fixes inline plots in tutorial

- .github/workflows/ci.yml
CD script added to `ci.yml`
Closes [testing CD script](https://github.com/ploomber/dummy/issues/2)
> CD for SKE added

- .github/workflows/ci.yml
- docs/classification/basic.md
- docs/classification/calibration.md
- docs/classification/compare.md
- docs/classification/evaluate.md
- docs/classification/grid_search.md
- docs/classification/imbalance.md
- docs/comparison/NotebookCollection.md
- docs/comparison/SQLiteTracker.md
- docs/comparison/nbdb.md
- docs/comparison/nn_tracking.md
- docs/comparison/report.md
- docs/dimensionality_reduction/pca.md
- docs/optimization/feature_ranking.md
- docs/optimization/grid_search.md
- docs/quickstart/classification.md
- docs/quickstart/clustering.md
- docs/quickstart/regression.md
- docs/reference/developer.md
- docs/reference/matplotlib.md
- docs/regression/RegressionPlots.md
- pyproject.toml
context: https://github.com/ploomber/contributing/issues/22
this PR runs flake8 on notebook files (ipynb, md) in the CI process and it formats existing notebooks
----
:books: Documentation preview :books:: https://sklearn-evaluation--280.org.readthedocs.build/en/280/
> running flake8 on notebooks during CI + formatting 

- CHANGELOG.md
- docs/_toc.yml
- docs/classification/micro_macro.md
- src/sklearn_evaluation/plot/classification_report.py
Added tutorial for micro and macro average scores
Closes #240 #284 
----
:books: Documentation preview :books:: https://sklearn-evaluation--285.org.readthedocs.build/en/285/
> Micro macro average

- CHANGELOG.md
- docs/quickstart/clustering.md
Edited quickstart clustering doc so that instead of manually creating a PCA visualization it uses our API's `plot.pca` function
Closes #276 
----
:books: Documentation preview :books:: https://sklearn-evaluation--288.org.readthedocs.build/en/288/
> quickstart clustering doc update

- .github/workflows/ci.yml
- examples/silhouette_plot_text.py
- setup.py
This PR is to test CI packages caching
----
:books: Documentation preview :books:: https://sklearn-evaluation--295.org.readthedocs.build/en/295/
> Testing CI caching

- CHANGELOG.md
- docs/_toc.yml
- docs/api/plot.rst
- docs/classification/cm_interactive.md
- docs/requirements.txt
- examples/confusion_matrix_interactive.py
- setup.py
- src/sklearn_evaluation/plot/__init__.py
- src/sklearn_evaluation/plot/confusion_matrix_interactive.py
- src/sklearn_evaluation/plot/plot.py
- tests/test_interactive_confusion_matrix.py
Interactive confusion matrix plots.
Closes #185 
----
:books: Documentation preview :books:: https://sklearn-evaluation--275.org.readthedocs.build/en/275/
> Interactive confusion matrix

- docs/requirements.txt
Closes #x 
----
:books: Documentation preview :books:: https://sklearn-evaluation--310.org.readthedocs.build/en/310/
> pins jupyter-book

- docs/classification/report_comparison.md
- docs/classification/report_evaluation.md
- examples/report_comparison.py
- examples/report_evaluation.py
- src/sklearn_evaluation/report/__init__.py
- src/sklearn_evaluation/report/model_evaluator.py
- src/sklearn_evaluation/report/model_heuristics.py
- src/sklearn_evaluation/report/models_comparer.py
- tests/conftest.py
- tests/test_grid_search.py
Closes #x 
----
:books: Documentation preview :books:: https://sklearn-evaluation--315.org.readthedocs.build/en/315/
> fixes broken links

- .github/workflows/ci.yml
- examples/calibration_curve_add.py
no longer running examples in the CI to make it faster, they're still executed in readthedocs so if they fail, we'll know
Closes #x 
----
:books: Documentation preview :books:: https://sklearn-evaluation--324.org.readthedocs.build/en/324/
> skip examples/ in ci

- .github/workflows/ci.yml
- doc/environment.yml
Closes #x 
----
:books: Documentation preview :books:: https://sklearn-evaluation--325.org.readthedocs.build/en/325/
> fix doc/environment.yml for Apple ARM

- .github/workflows/ci.yml
- doc/comparison/NotebookCollection.md
- doc/environment.yml
- environment.yml
- setup.py
Closes #x 
----
:books: Documentation preview :books:: https://sklearn-evaluation--326.org.readthedocs.build/en/326/
> removing references to papermill and cleaning up setup

- src/sklearn_evaluation/plot/calibration.py
- src/sklearn_evaluation/plot/plot.py
- src/sklearn_evaluation/plot/precision_recall.py
- src/sklearn_evaluation/plot/roc.py
- tests/test_abstract_plot.py
- tests/test_roc.py
- Added a generic implementation for plot __sub__ and __add__ method. 
- Added unit tests for plot __sub__ and __add__ method.
Closes #236 
----
:books: Documentation preview :books:: https://sklearn-evaluation--320.org.readthedocs.build/en/320/
> moving plot's sub and add methods to abstract class

- doc/optimization/feature_selection.md
- doc/optimization/underfitting_overfitting.md
- src/sklearn_evaluation/nb/NotebookDatabase.py
- src/sklearn_evaluation/plot/calibration.py
- src/sklearn_evaluation/plot/classification_report.py
- src/sklearn_evaluation/plot/confusion_matrix_interactive.py
- src/sklearn_evaluation/plot/cumulative_gain_lift_curve.py
- src/sklearn_evaluation/plot/feature_ranking.py
- src/sklearn_evaluation/plot/grid_search.py
- src/sklearn_evaluation/plot/ks_statistics.py
- src/sklearn_evaluation/plot/pca.py
- src/sklearn_evaluation/plot/precision_recall.py
- src/sklearn_evaluation/plot/regression.py
- src/sklearn_evaluation/plot/roc.py
- src/sklearn_evaluation/plot/style.py
- src/sklearn_evaluation/plot/target_analysis.py
- tests/conftest.py
- tests/nb/test_NotebookCollection.py
- tests/test_abstract_plot.py
- tests/test_calibration_curve.py
- tests/test_feature_ranking.py
- tests/test_grid_search.py
- tests/test_pca.py
- tests/test_random_forest_classifier_grid.py
- tests/test_skeval_telemetry.py
Closes #x 
----
:books: Documentation preview :books:: https://sklearn-evaluation--331.org.readthedocs.build/en/331/
> formatting

- readthedocs.yaml
Reverted to echo method, deleted `vcheck.md` file and any `.DS_Store` files
Closes https://github.com/ploomber/contributing/issues/26
----
:books: Documentation preview :books:: https://sklearn-evaluation--334.org.readthedocs.build/en/334/
> version check disable sk-eval
